### ISSUE TITLE
Changing directions quickly causes uncontrollable driving

### ISSUE THREAD

**Issue by ehamwey** [REVrobotics/MAXSwerve-Java-Template#10]
When using the slew rate limiter, if the driver quickly changes direction from forward and back, multiple times per second, after a few seconds the robot drives at full speed in one direction uncontrollably. 

We've tested with both an older version of the template without the rate limiter, as well as disabling the slew rate limiter via the `rateLimit` parameter of the `drive` function. All test have been done on a completely vanilla copy of the template, with both WPILib `2023.2.1` as in the template, and `2023.4.2`. 

https://user-images.githubusercontent.com/9936886/224512561-5b24d621-76af-4ef3-8e32-0af5ff21d4d2.mp4

**Comment by NoahAndrews** [comment]
We haven't been able to reproduce this, so for now, we'll handle this within our email system. We've asked you some further questions there to try to help figure out what's going on. If it does turn out to be an issue with the MAXSwerve template, we'll reopen this issue.
