### ISSUE TITLE
2024 compatibility

### ISSUE THREAD

**Issue by kbyquist** [REVrobotics/MAXSwerve-Java-Template#18]
Template is not up to date with 2024 vendor api changes. 

[This commit](https://github.com/kbyquist/2024MaxSwerve/commit/d7287b11e1f504150f0058192ed3b7cd41da331e) to my repo has necessary changes to get a buildable 2024 code base

**Comment by jfabellera** [comment]
Thanks for submitting an issue. We will have update the repo shortly.
