### ISSUE TITLE
using the bulit-in relative encoder for the turning motors?

### ISSUE THREAD

**Issue by Gloobyy** [REVrobotics/MAXSwerve-Java-Template#20]
We do not have absolute encoders for our swerve module, is there a way to use the built-in encoders instead of the relative ones that are in the code? we attempted to change it ourselves but when we enable the robot it freaks out. Are we just dumb, or is it something else?
[MAXSwerveModule.zip](https://github.com/REVrobotics/MAXSwerve-Java-Template/files/14196470/MAXSwerveModule.zip)
this is the changes we made, and we tried to use the same encoders as the driving motors but the robot crashed without removing the invert on the turning encoder in constants.java and when we removed it, the motors for turning just freaked out.

**Comment by NoahAndrews** [comment]
Without an absolute encoder, you would need to manually align the wheels every time you turn on the robot. You would be much better off just getting the encoders.

**Comment by NoahAndrews** [comment]
Are you using MAXSwerve modules? The kit includes the encoders.

**Comment by Gloobyy** [comment]
[https://www.swervedrivespecialties.com/products/mk4i-swerve-module?variant=46872600084781](url) 
We are using the mk4i modules from swerve drive specialties. They have a cancoder on them but I had assumed they were for

**Comment by NoahAndrews** [comment]
Yes, the external absolute encoder is for steering, not distance tracking.
